apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: gitops-friendly-machinesets
spec:
  image: openshift.io/gitops-friendly-machinesets-operator-catalog:v0.2.0
  sourceType: grpc
